# Generated by Django 4.0.4 on 2022-04-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0002_rename_user_userprofile_alter_business_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='name',
            new_name='neighbourhood_name',
        ),
    ]
