# Generated by Django 4.0.4 on 2022-04-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0003_rename_name_neighbourhood_neighbourhood_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='Bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
