# Generated by Django 4.0.4 on 2022-04-17 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0008_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighbourhood_id',
            new_name='neighbourhood_name',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(default='default.png', upload_to='neighbourhood/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile/'),
        ),
    ]
