# Generated by Django 4.0.4 on 2022-04-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0010_alter_neighbourhood_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='neighbourhood_id',
            new_name='neighbourhood_name',
        ),
    ]
