# Generated by Django 4.0.4 on 2022-04-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0011_rename_neighbourhood_id_userprofile_neighbourhood_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='your_id',
            new_name='national_identity_no',
        ),
    ]
