# Generated by Django 4.0.4 on 2022-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0012_rename_your_id_userprofile_national_identity_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
    ]
